# [Error handling patterns](https://andreabergia.com/blog/2023/05/error-handling-patterns/)

El manejo de errores es un aspecto fundamental de la programaci√≥n. A menos que est√©s escribiendo "hola mundo", necesitar√°s manejar errores en tu c√≥digo. En esta publicaci√≥n, analizar√© un poco los enfoques m√°s comunes utilizados por varios lenguajes de programaci√≥n.

## C√≥digos de error de retorno [](https://andreabergia.com/blog/2023/05/error-handling-patterns/#return-error-codes)

Esta es una de las estrategias m√°s antiguas: si una funci√≥n puede fallar, simplemente puede devolver un c√≥digo de error, a menudo un n√∫mero negativo o "``null``". Esto es extremadamente com√∫n en C, por ejemplo:
```c
FILE* fp = fopen("file.txt" , "w");
if (!fp) {
  // some error occurred
}
```

Este enfoque es muy simple, tanto para implementar como para comprender. Tambi√©n es extremadamente eficiente para ejecutar, ya que solo implica una llamada de funci√≥n est√°ndar, con un valor de retorno - no se necesita soporte en tiempo de ejecuci√≥n ni asignaciones. Sin embargo, tiene algunas desventajas:

- es f√°cil para los usuarios de las funciones olvidarse del manejo de errores. Por ejemplo, `printf` en C _puede_ fallar, ¬°pero no he visto muchos programas que verifiquen su c√≥digo de retorno!
- es molesto propagar errores a lo largo de la pila de llamadas, especialmente si su c√≥digo tiene que manejar m√∫ltiples fallas diferentes (abrir un archivo, escribir en √©l, leer de otro...)
- a menos que su lenguaje de programaci√≥n admita m√∫ltiples valores de retorno, es molesto si tiene que devolver un valor v√°lido _o_ un error. Esto lleva a que muchas funciones en C y C++ tengan que pasar el almacenamiento para el valor de retorno de "√©xito" como un puntero que ser√° llenado por la funci√≥n, haciendo algo como:

```c
my_struct *success_result;
int error_code = my_function(&success_result);
if (!error_code) {
  // puede utilizar success_result
}
```

[Go](https://go.dev/) ha elegido este enfoque para su manejo de errores. Sin embargo, dado que ``Go`` permite m√∫ltiples valores de retorno de una funci√≥n, este patr√≥n se vuelve un poco m√°s ergon√≥mico y muy com√∫n:

```go
user, err = FindUser(username)
if err != nil {
    return err
}
```

La variante ``Go`` del patr√≥n es simple, efectiva y permite la propagaci√≥n de errores al autor de la llamada. Por otro lado, siento que es bastante repetitiva y distrae un poco de la l√≥gica empresarial real. ¬°Sin embargo, no he escrito suficiente ``Go`` como para saber si esa impresi√≥n desaparece despu√©s de un tiempo! üòÖ

## Excepciones¬†[](https://andreabergia.com/blog/2023/05/patrones-de-manejo-de-errores/#exceptions)
Las excepciones son probablemente el patr√≥n de manejo de errores m√°s utilizado. El enfoque `try/catch/finally`¬†funciona bastante bien y es bastante sencillo de usar. Las excepciones se volvieron extremadamente populares durante los a√±os 90 y 2000 y han sido adoptadas por muchos lenguajes como ``Java``, ``C#`` o ``Python``.

En comparaci√≥n con los c√≥digos de error, las excepciones tienen algunas ventajas:

- conducen naturalmente a una separaci√≥n entre el "camino feliz" y el camino de manejo de errores
- se expandir√°n autom√°ticamente a trav√©s de la pila de llamadas
- ¬°y no puedes olvidarte de manejar los errores!

Sin embargo, tambi√©n tienen algunas desventajas: requieren un soporte espec√≠fico en tiempo de ejecuci√≥n y generalmente suponen una sobrecarga de rendimiento considerable. Adem√°s, y mucho m√°s importante, tienen un efecto de ‚Äúlargo alcance‚Äù: una excepci√≥n podr√≠a ser lanzada por alg√∫n c√≥digo y detectada por un controlador de excepciones muy alejado en la pila de llamadas, lo que perjudica la claridad.

Adem√°s, no es obvio si una funci√≥n lanzar√° alguna excepci√≥n con solo mirar su firma.

C++ intent√≥ solucionar este problema con la causa `throws`, que se us√≥ tan poco que termin√≥ siendo [obsoleta en C++17](https://en.cppreference.com/w/cpp/language/except_spec)¬†y eliminada en ``C++20``. Desde entonces, intent√≥ introducir [`noexcept`](https://en.cppreference.com/w/cpp/language/noexcept_spec), pero no he escrito suficiente C++ moderno como para saber lo popular que es.

``Java`` intent√≥ usar ["excepciones comprobadas"](https://www.baeldung.com/java-checked-unchecked-exceptions), es decir, excepciones que _ten√≠as_ que declarar como parte de la firma, pero ese enfoque se consider√≥ un fracaso tal que los marcos modernos como ``Spring`` solo usan "excepciones en tiempo de ejecuci√≥n", y los lenguajes ``JVM`` como ``Kotlin`` [se deshicieron del concepto](https://kotlinlang.org/docs/exceptions.html#the-nothing-type) por completo. Al final, no hay una buena manera de saber si una llamada a un m√©todo arrojar√° o no una excepci√≥n, y por lo tanto terminas con un poco de l√≠o.

## Devoluciones de llamadas de error [](https://andreabergia.com/blog/2023/05/error-handling-patterns/#error-callbacks)

Otro enfoque, muy com√∫n en el mundo de ``JavaScript``, es utilizar [devoluciones de llamadas](https://kotlinlang.org/docs/exceptions.html#the-nothing-type) que se invocar√°n cuando una funci√≥n tenga √©xito o falle. Esto a menudo se combina con la programaci√≥n ``asincr√≥nica``, donde la ``E/S`` se realiza en segundo plano sin bloquear el flujo de ejecuci√≥n.

Por ejemplo, es bastante com√∫n que las funciones de ``E/S`` de ``Node``.JS acepten una devoluci√≥n de llamada con dos argumentos `(error, resultado)`, por ejemplo:

```javascript
const fs = require('fs');
fs.readFile('some_file.txt', (err, result) => {
  if (err) {
    console.error(err);
    return;
  }

  console.log(result);
});
```

Sin embargo, este enfoque a menudo conduce al llamado problema del [[Callback Hell]] [‚Äúinfierno de las devoluciones de llamadas‚Äù](http://callbackhell.com/), ya que una devoluci√≥n de llamada podr√≠a necesitar invocar m√°s `E/S` `asincr√≥nicas`, lo que a su vez necesita m√°s devoluciones de llamadas, etc., terminando con un c√≥digo desordenado y dif√≠cil de seguir.

Las versiones modernas de ``JavaScript`` han intentado hacer que el c√≥digo sea m√°s legible introduciendo [_promesas_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise):

```javascript
fetch("https://example.com/profile", {
      method: "POST", // or 'PUT'
})
  .then(response => response.json())
  .then(data => data['some_key'])
  .catch(error => console.error("Error:", error));
```

El paso final en el patr√≥n de promesas ha sido la adopci√≥n por parte de JavaScript del patr√≥n `async/await`, popularizado [por C#](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/async-scenarios), que hace que la ``E/S asincr√≥nica`` termine pareci√©ndose bastante al c√≥digo sincr√≥nico con excepciones cl√°sicas:

```javascript
async function fetchData() {
  try {
    const response = await fetch("my-url");
    if (!response.ok) {
      throw new Error("Network response was not OK");
    }
    return response.json()['some_property'];
  } catch (error) {
    console.error("There has been a problem with your fetch operation:", error);
  }
}
```

El uso de devoluciones de llamadas [[callbacks]] para el manejo de errores es un patr√≥n importante que se debe conocer, no solo en ``JavaScript`` (la gente lo ha estado usando en C durante a√±os, por ejemplo). Sin embargo, ya no es muy com√∫n: es probable que est√©s usando alguna forma de `async/await`.
## Resultado de lenguajes funcionales¬†[](https://andreabergia.com/blog/2023/05/error-handling-patterns/#result-from-functional-languages)

El √∫ltimo patr√≥n que quiero comentar tiene su origen en lenguajes funcionales, como¬†[Haskell](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Either.html), pero se ha vuelto un poco m√°s com√∫n dada la explosi√≥n de popularidad de¬†[Rust](https://andreabergia.com/blog/2022/11/languages-opinion-part-two-rust/).

La idea es tener un tipo¬†`Result`¬†como:

```rust
enum Result<S, E> {
  Ok(S),
  Err(E)
}
```

Este es un tipo que tiene dos variantes: una expresa √©xito y la otra, un fracaso. Una funci√≥n que devuelve un resultado devolver√° la variante `Ok`, opcionalmente con algunos datos, o la variante `Err` con algunos detalles del error. El llamador de la funci√≥n normalmente utilizar√° la coincidencia de patrones para manejar ambos casos.

Para hacer que los errores aparezcan en la pila de llamadas, normalmente escribir√≠as un c√≥digo como este:

```rust
let result = match my_fallible_function() {
  Err(e) => return Err(e),
  Ok(some_data) => some_data,
};
```

Este patr√≥n es tan com√∫n que ``Rust`` introdujo un¬†_operador_¬†completo en el lenguaje (el signo de interrogaci√≥n¬†`?`) para simplificar el c√≥digo anterior:

```rust
let result = my_fallible_function()?;   // Notice the "?"
```

La ventaja de este enfoque es que hace que el manejo de errores sea expl√≠cito y seguro en cuanto a tipos, ya que el compilador garantiza que se manejen todos los resultados posibles.

En los lenguajes que lo admiten, `Result` es t√≠picamente [Monad](https://en.wikipedia.org/wiki/Monad_(functional_programming)), lo que permite componer funciones que pueden fallar sin tener que usar bloques ``try/catch`` o declaraciones ``if`` anidadas.
En los lenguajes que lo admiten, `Result` es t√≠picamente [Monad](https://en.wikipedia.org/wiki/Monad_(functional_programming)) [[Monad]], lo que permite componer funciones que pueden fallar sin tener que usar bloques ``try/catch`` o declaraciones if anidadas.

# Conclusiones¬†[](https://andreabergia.com/blog/2023/05/patrones-de-manejo-de-errores/#conclusiones)

Dependiendo del lenguaje de programaci√≥n que uses y de tu proyecto, terminar√°s usando mayoritariamente o exclusivamente uno de estos patrones.

Sin embargo, yo dir√≠a que el patr√≥n `Result` es mi favorito. Por supuesto, su adopci√≥n no se limita a los lenguajes funcionales; por ejemplo, en mi empleador [lastminute.com](https://lastminute.com/)¬†usamos la biblioteca [Arrow](https://arrow-kt.io/)¬†en ``Kotlin``, que contiene un tipo `Either`¬†muy inspirado en ``Haskell``. Planeo escribir una publicaci√≥n al respecto, as√≠ que gracias por leer esto y estad atentos üòä.